"""Data models and schemas for The Red Room."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class VulnerabilityType(str, Enum):
    """Types of vulnerabilities that can be detected."""
    RACE_CONDITION = "race_condition"
    AUTH_BYPASS = "auth_bypass"
    INJECTION = "injection"
    LOGIC_FLAW = "logic_flaw"
    CRYPTO_WEAKNESS = "crypto_weakness"
    TIMING_ATTACK = "timing_attack"


class AgentStatus(str, Enum):
    """Status of agent execution."""
    IDLE = "idle"
    ANALYZING = "analyzing"
    EXPLOITING = "exploiting"
    PATCHING = "patching"
    COMPLETED = "completed"
    FAILED = "failed"


class Hypothesis(BaseModel):
    """Attack hypothesis generated by Agent I."""
    vulnerability_type: VulnerabilityType
    confidence_score: float = Field(ge=0.0, le=1.0)
    affected_endpoints: List[str]
    invariant_break: Dict[str, str]
    attack_hypothesis: Dict[str, Any]
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ExploitResult(BaseModel):
    """Result of exploit execution by Agent II."""
    exploit_successful: bool
    evidence: Dict[str, Any]
    reproducibility_score: float = Field(ge=0.0, le=1.0)
    execution_time_ms: int
    shadow_namespace: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PatchResult(BaseModel):
    """Result of patch generation by Agent III."""
    patch: str
    explanation: str
    complexity_analysis: Dict[str, str]
    regression_tests: str
    performance_delta: Dict[str, float]
    pr_url: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ExecutionState(BaseModel):
    """Overall execution state."""
    execution_id: str
    status: AgentStatus
    git_commit: str
    hypothesis: Optional[Hypothesis] = None
    exploit_result: Optional[ExploitResult] = None
    patch_result: Optional[PatchResult] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
